### PR TITLE
Translate Postgres error codes into atoms.

### PR DESCRIPTION
**Pull request by MSch**
#51

### CODE REVIEW

**Comment by MSch** [comment]
Regarding duplicated names, I looked at their usage in Postgres master

```elixir
{:string_data_right_truncation, ["22001", "01004"]} # only 22001 is used
{:modifying_sql_data_not_permitted, ["38002", "2F002"]} # non used
{:prohibited_sql_statement_attempted, ["38003", "2F003"]} # only 2F003 is used
{:reading_sql_data_not_permitted, ["38004", "2F004"]} # non used
{:null_value_not_allowed, ["39004", "22004"]} # only 22004 is used
```

This makes me think we should simplify `name_to_codes` to always return a single code (the one that's used or the ones in classes 22 Data Exception and 2F SQL Routine Exception as opposed to classes 01 Warning, 38 External Routine Exception, 39 External Routine Invocation Exception).

**Comment by ericmj** [comment]
+1 for simplifying `name_to_codes`.

**Comment by ericmj** [comment]
Merged manually, thanks @MSch!

**Comment by MSch** [comment]
@ericmj I've got some work in progress locally regarding the `name_to_code` simplification. Wanted to force push here, but will just open another PR

**Comment by ericmj** [comment]
@MSch Please take a look at the last commit. Was that what you had in mind?

**Comment by ericmj** [comment]
If not please send another PR :)

**Comment by MSch** [comment]
Oh yeah that was exactly that. Thanks! :)

**Pull request merged**
