### PR TITLE
Improved support of hstore for case when hstore extension is created inside a PG schema

### PR DESCRIPTION
**Pull request by romul**
I've tried to remove schema prefix for TypeInfo fields in Types.build_types/1. But it looks like a strange hack and could lead to side-effects besides.
And in any case it won't be enough.
Types are preloaded with Types.bootstrap_query/2, which also use send matchers in SQL query like 
``` sql
SELECT t.oid, t.typname, t.typsend, t.typreceive, t.typoutput, t.typinput,
       t.typelem, coalesce(r.rngsubtype, 0), ARRAY (
  SELECT a.atttypid
  FROM pg_attribute AS a
  WHERE a.attrelid = t.typrelid AND a.attnum > 0 AND NOT a.attisdropped
  ORDER BY a.attnum
)
FROM pg_type AS t
LEFT JOIN pg_range AS r ON r.rngtypid = t.oid
WHERE
  t.typname::text = ANY ((ARRAY[])::text[]) OR
  t.typsend::text = ANY ((ARRAY['array_send', 'range_send', 'record_send', 'cidsend', 'xidsend', 'regtypesend', 'regclasssend', 'regoperatorsend', 'regopersend', 'regproceduresend', 'regprocsend', 'oidsend', 'hstore_send', 'unknownsend', 'tidsend', 'enum_send', 'interval_send', 'timestamptz_send', 'timestamp_send', 'timetz_send', 'time_send', 'date_send', 'uuid_send', 'numeric_send', 'float8send', 'float4send', 'int8send', 'int4send', 'int2send', 'byteasend', 'varcharsend', 'citextsend', 'textsend', 'bpcharsend', 'boolsend', 'void_send'])::text[]) OR
  t.typreceive::text = ANY ((ARRAY[])::text[]) OR
  t.typoutput::text = ANY ((ARRAY[])::text[]) OR
  t.typinput::text = ANY ((ARRAY[])::text[])
``` 

I think, we should admit, that hstore could not be matched by typsend, else we will end up with ugly hacks like removing schema from t.typsend::text directly in SQL.
This pull request eliminates need in writing own Postgrex extension for custom hstore.

### CODE REVIEW

**Comment by ericmj** [comment]
I'm afraid you are right that there is no good way of matching without the schema so we should use your proposal of matching against the type instead. Unfortunately this PR only fixes hstore but many more types can be broken by schemas.

Could you amend the PR to match against type names for all types except the generic ones? Can you also make sure we create the hstore extension inside a schema so we properly test this behaviour? Thank you for finding the bug and proposing a fix.

**Comment by romul** [comment]
> Unfortunately this PR only fixes hstore but many more types can be broken by schemas.

I'm pretty sure, that only types from `SELECT * FROM pg_available_extensions` could have schema prefix. So, I'm going to add a fix only for citext, b/c other types from PG extensions have no support in postgrex yet. And to make this fix more explicit to avoid confusion in further work on adding new types.

> Can you also make sure we create the hstore extension inside a schema so we properly test this behaviour? 

Yes, it makes sense. Will do.

**Comment by ericmj** [comment]
> I'm pretty sure, that only types from SELECT * FROM pg_available_extensions could have schema prefix. So, I'm going to add a fix only for citext, b/c other types from PG extensions have no support in postgrex yet. And to make this fix more explicit to avoid confusion in further work on adding new types.

It would be more consistent to change all non-generic types to use type name and would be easier to understand for future contributors.

**Comment by romul** [comment]
I understand your point, but take a look at the commit first. Maybe it is clear enough for maintenance purposes.

**Comment by ericmj** [comment]
That's great, will merge after CI passes.

**Comment by romul** [comment]
Great! I've also added some additional tests.

**Comment by ericmj** [comment]
Thank you!

**Pull request merged**
