### PR TITLE
Optimize tag decoding

### PR DESCRIPTION
**Pull request by josevalim**
The first commit moves the enum based implementation into binary decoding. The new implementation assumes that once an integer is found in the tag, only integers will be expected. I.e. we can have "INSERT 0 1" and "SELECT 1" and "ROLLBACK" but never "COMMAND 0 ANOTHER 1". @ericmj is this assumption correct?

The second commit inlines common commands: insert, select, update, delete, begin, rollback and commit.

### CODE REVIEW

**Comment by josevalim** [comment]
The motivation is that @fishcakez found decode_tag sometimes was taking up to 17% of the stack when profiling.

**Comment by fishcakez** [comment]
It might be that tracing interferes with the real data. I have rerun the benchmark I used before and got between 2.5% and 5% reduction in time using this branch. So likely I need to find a better benchmark. Once we do a benchmark with a remote postgres its hopefully that the performance difference on master compared to v0.10.0 or this branch become meaningless.

**Comment by josevalim** [comment]
In any case, I think we should at least merge the first commit. The implementation is better. The second commit is inlining and therefore is optional.

**Comment by fishcakez** [comment]
Yeah definitely I was just wondering about the large % of time and not being able to say exactly how much reduction it gave. The docs say the format is `COMMAND`, `COMMAND rows` or  `INSERT oid rows`.

**Comment by fishcakez** [comment]
http://www.postgresql.org/docs/9.5/static/protocol-message-formats.html See CommandComplete. I think we should just special case the listed commands with a row value, otherwise just do lowercase -> to_atom (if not a common command).

**Comment by fishcakez** [comment]
Also lets use `:erlang.binary_to_integer` instead because we never need the tail except for `INSERT`. For `INSERT` we can just skip the integers until we get a space then to the BIF on the tail.

**Comment by josevalim** [comment]
@fishcakez thanks. pushed a new implementation!

**Comment by fishcakez** [comment]
The stack looks much better now. The failure on the branch is because its no based on master. :shipit:

**Comment by josevalim** [comment]
Merging this since @fishcakez validated the assumption was correct. :)

**Pull request merged**
