### PR TITLE
Support oid and all its aliases

### LINKED ISSUE #63: Support oid and all its aliases
oid
regproc
regprocedure
regope
regoperator
regclass
regtype
regconfig
regdictionary

### PR DESCRIPTION
**Pull request by MSch**
Fixes #63

I noticed that there are a few places where oid is treated as int32 not as uint32. I can fix that in a separate PR.

### CODE REVIEW

**Comment by ericmj** [comment]
Would it be possible to move the reg* types to the binary extension? It would be preferred to have them in binary because that means they will automatically work in arrays and composite types. Postgrex does not handle arrays and composites in text format.

**Comment by MSch** [comment]
@ericmj That's what I started with, but the binary protocol just handed me 4 bytes (which I suspect are the OID of the type) and not a string representation.

**Comment by MSch** [comment]
I tried to catch all occurrences where OIDs where encoded as signed integers. Not sure if I missed any.

**Comment by ericmj** [comment]
Nice job of fixing all the occurrences of signed oids.

All the reg* types are oids. I would prefer to keep them as integers, if you want the string representation you can cast to text.

```psql
ericmj=# SELECT 96::regoperator::text;
        text
--------------------
 =(integer,integer)
(1 row)
```

**Comment by MSch** [comment]
@ericmj would I be able to do `query("SELECT nextval($1);", ["name_of_the_sequence"])` with that? I guess that wouldn't work, since we need to send an oid then too?

**Comment by MSch** [comment]
I think if we go down that route we should only support `oid`, and force users to manually cast to oid, e.g. `SELECT 'pg_type'::regclass::oid`, because I think getting an integer for a regclass is very unintuitive.

**Comment by ericmj** [comment]
Where do you get the string representation of the sequence from? I think the following should work: `query("SELECT nextval($1::text::regclass);", ["name_of_the_sequence"])`

**Comment by MSch** [comment]
It's "hardcoded", same as I hardcode the names of my tables in the Ecto models.

Yeah that would work, interestingly `query("SELECT nextval($1::text);", ["name_of_the_sequence"])` also works, I guess it's auto-casted?

**Comment by MSch** [comment]
Anyhow, not accepting strings for regclass types is IMO definitely going to badly suprise people. I'd prefer to keep them as text for this reason.

**Comment by ericmj** [comment]
It's unfortunate though because they wont work in arrays or composite types.

**Comment by MSch** [comment]
@ericmj After sleeping over it I agree with you. I would like to add a specific error message explaining what's going on if the user attempts to encode a string as regclass and friends, that should catch the most-common problem I anticipate, people calling `nextval($1)` with a string.

**Comment by MSch** [comment]
@ericmj ready from my side. Would it be possible to release 0.8.1 with this?

**Comment by ericmj** [comment]
Beautiful. Thanks @MSch. Will try to release 0.8.1 today.

**Pull request merged**
