### PR TITLE
Enforce bounds of integers and integer ranges.

### PR DESCRIPTION
**Pull request by MSch**
Previously the encoded integer (ranges) would be decoded by Postgres as wrapped around.

### CODE REVIEW

**Comment by MSch** [comment]
> ```
> # TODO: Encode ranges generically with typbasetype
> ```

This will need to consider that a range's upper bound is different from the base types' upper bound.

**Comment by MSch** [comment]
Also since 0.7 the way Postgrex no longer returns encoding errors, is the way of just erroring with `:function_clause` now the recommended way?
https://github.com/ericmj/postgrex/blob/v0.7.0/lib/postgrex/types.ex#L115

**Comment by ericmj** [comment]
Thanks!

> Also since 0.7 the way Postgrex no longer returns encoding errors, is the way of just erroring with :function_clause now the recommended way?

Yes, it was too difficult to catch all errors so an extension can return any error now. I have been thinking about wrapping extension errors so they are presented to users in a better way, but I'm not convinced it's a good idea, wdyt?

What I want to do though (which `throw {:postgrex_encode, ...}` sort of achieved) is to catch extension errors, log it and reply with an error to the user but keep the connection alive and reset it to a good state. Bad queries and parameters should ideally not kill the connection.

**Comment by MSch** [comment]
I think extension errors (both user defined and postgrex-supplied types are called extensions now right?) definitely should be wrapped and presented as a `Postgrex.Error`, because they are often very similar to errors like `unique_violation` (which nowadays even deliver which column was responsible) that we want to present to the end user ("there's already an account with email..." instead of hoping the race never happens and Ecto's uniqueness check is good enough, but when it does happen we crash), e.g. "that number is out of range" or even more interesting/harder to rebuild ourselves: "feb 31 is not a valid date".

In 0.7 I noticed how the "unable to encode" error doesn't have a code or anything to distinguish it easily (matching on `message` is not really an option), I think that should be added too (Maybe something like `extension: [column: :id, extension: :int4]` instead of `postgres: ...`]? Also IMO all Postgres errors are worth translation into atoms (the [naming scheme](http://www.postgresql.org/docs/9.4/static/errcodes-appendix.html) is already perfect))

**Comment by MSch** [comment]
> Bad queries and parameters should ideally not kill the connection.

Under which circumstances would they drop the connection?

RhodiumToad dropped some wisdom re resetting the connection state: Postgres errors always abort the smallest enclosing subtransaction, to reset the connection only a `ROLLBACK`/`RELEASE SAVEPOINT` should be necessary, except for [`SET SESSION`](http://www.postgresql.org/docs/9.3/static/sql-set.html) and session-level advisory locks (`pg_advisory_lock`).

So it seems to me there is no circumstance where dropping the connection is really necessary. Though this makes me think Ecto should have a way for the user to decide to close the connection (because of session-level SETs and advisory locks)

**Comment by ericmj** [comment]
> Under which circumstances would they drop the connection?

For example, an unhandled error in an extension. A bad query would result in a syntax error from the server and we send a SYNC message that resets the connection. A bad parameter, that causes an error from an extension should reply with an error to the caller and abort the query with a SYNC message.

> So it seems to me there is no circumstance where dropping the connection is really necessary. Though this makes me think Ecto should have a way for the user to decide to close the connection (because of session-level SETs and advisory locks).

I would say don't ever do session-level SETs or any other things that changes the connection globally over transactions. Use your own connection pool for that. In fact, poolboy is not a good pooler here because it will check in connections if the caller dies which can potentially leave the connection in a bad state.

**Pull request merged**
