### PR TITLE
Take a new option to set the search_path on connection

### PR DESCRIPTION
**Pull request by JonathanTron**
Hi, I don't know if it's the best way to do it but here's a simple addition which allows to set the search_path when opening a connection.

Here's my use-case:

I'm assigning each customer a PostgreSQL schema, I would like to access it via `Ecto`. For this I need to be able to set the `search_path` to the customer schema before issuing queries for a given customer. 
Calling `SET search_path TO xxx` before each query being a bad idea, I would like to have a way to create an `Ecto.Repo` per customer which would then have all the connections using the defined `search_path`. 
I've managed to generate the `Ecto.Repo` for a customer on-demand, but then I discovered there was no way in `postgrex` to set the `search_path` on connection (PostgreSQL `JDBC` drivers allows it since 9.4, `Sequel` also provide a way to set it when opening a connection).

### CODE REVIEW

**Comment by josevalim** [comment]
That sounds a good way to solve this problem. Some have opened an issue on Ecto about this, but moving to the Postgrex connection is better because there isn't a risk of us accidentally not doing it in Ecto because we lost track of the connection.

**Comment by JonathanTron** [comment]
Thanks José, this indeed frees Ecto from the responsibility to set the search_path. I'm not even sure it would be possible to do only in Ecto unless you open a new transaction block around all queries which should have the same search_path, which is not practical and would make the performance awful.

My goal is to be able to use a different Ecto.Repo per request in a Phoenix app.

**Comment by ericmj** [comment]
I would prefer to solve it in ecto with an on_connect hook. There's a number of parameters you can set when starting a connection so why limit us to search_path and support in the driver?

**Comment by JonathanTron** [comment]
Indeed, that would be great, but isn't postgrex responsible for handling the pool of connection? How is it possible to have an `on_connect` this way in Ecto?

**Comment by ericmj** [comment]
No, ecto handles the pool and wraps the connection.

**Comment by JonathanTron** [comment]
Ok that is great then. I would gladly work on a solution on this front then if you can help me pinpoint the elements which needs to be adapted.

**Pull request closed without merging**
