### PR TITLE
Add failing test case for floats with `0.001` format.

### PR DESCRIPTION
**Pull request by laurocaetano**
Just opened this pull request to demonstrate the issue reported in https://github.com/elixir-lang/ecto/issues/547

I haven't had time to fix it, but I'll work on it this weekend.

### CODE REVIEW

**Comment by ericmj** [comment]
I will wait with merging until we have the fix. Thanks!

**Comment by ericmj** [comment]
Ping? Do you want me to grab it?

**Comment by laurocaetano** [comment]
Hi, sorry for the delay. I was playing with it last weekend, but I couldn't find a proper fix. 

The problem is the way it encodes the digits. It splits the number in two parts and then stores as an Integer. Example: `12.001` will be split in `12` and `001` and each part will be encoded as Integer. It will work fine for fractional that doesn't start with 0, otherwise it will continue encoding incorrectly. Makes sense?

I will have some time to work on this issue tonight, but I still having no clue about a effective way to fix it without changing how it is encoded. Do you have a hint?

**Comment by laurocaetano** [comment]
Just pinging with new information.

I had the chance to work on this issue yesterday with @bernardoamc and we concluded that my assumptions were completely wrong :cry: 

The encoding is, in fact, correct according to http://doxygen.postgresql.org/backend_2utils_2adt_2numeric_8c_source.html#l00265. The problem is somehow related with the float digits size. If we change the number from `1.001` to `1.00100` it's going to work fine. We have reached a temporary solution for this problem and we will update here later today.

Thanks :)

**Comment by laurocaetano** [comment]
Closed in favor of https://github.com/ericmj/postgrex/pull/67

**Pull request closed without merging**
